name: ChatPanel BUILD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_NUMBER: ${{ github.run_number }}
  PROJECT_NAME: "ChatPanel"

jobs:
  zip:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create ZIP
        run: |
          zip -r ${{ env.PROJECT_NAME }}.zip . \
          -x "*.git*" "*.github*" "README.md" "LICENSE" ".gitignore"
      - name: Upload ZIP Artifact
        uses: actions/upload-artifact@v4
        with:
          name: "${{ env.PROJECT_NAME }}.zip"
          path: "${{ env.PROJECT_NAME }}.zip"

      - name: Create Release
        if: github.event_name == 'push'
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: "${{ env.PROJECT_NAME }}.zip"
          name: "${{ env.PROJECT_NAME }} v${{ env.BUILD_NUMBER }}"
          tag: "build-${{ env.BUILD_NUMBER }}"
